<?xml version="1.0"?>
<?xml-model href="http://download.ros.org/schema/package_format3.xsd" schematypens="http://www.w3.org/2001/XMLSchema"?>
<package format="3">
  <name>om_pinocchio_task_impedance_controller</name>
  <version>0.1.0</version>
  <description>
    Pinocchio-based task-space impedance controller for OpenMANIPULATOR-X Arm (3D end effector position)
  </description>
  <maintainer email="pyo@robotis.com">Pyo</maintainer>
  <license>Apache 2.0</license>

  <buildtool_depend>ament_cmake</buildtool_depend>
  <buildtool_depend>ament_cmake_gtest</buildtool_depend>

  <depend>backward_ros</depend>
  <depend>controller_interface</depend>
  <depend>generate_parameter_library</depend>
  <depend>hardware_interface</depend>
  <depend>om_impedance_utilities</depend>
  <depend>pluginlib</depend>
  <depend>proxsuite</depend>
  <depend>rclcpp</depend>
  <depend>rclcpp_lifecycle</depend>
  <depend>pinocchio</depend>
  <depend>urdf</depend>

  <test_depend>ament_index_cpp</test_depend>
  <test_depend>open_manipulator_description</test_depend>

  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
