#ifndef PINOCCHIO_IMPEDANCE_CONTROLLER__VISIBILITY_CONTROL_H_
#define PINOCCHIO_IMPEDANCE_CONTROLLER__VISIBILITY_CONTROL_H_

#if defined _WIN32 || defined __CYGWIN__
#ifdef __GNUC__
#define PINOCCHIO_IMPEDANCE_CONTROLLER_EXPORT __attribute__((dllexport))
#define PINOCCHIO_IMPEDANCE_CONTROLLER_IMPORT __attribute__((dllimport))
#else
#define PINOCCHIO_IMPEDANCE_CONTROLLER_EXPORT __declspec(dllexport)
#define PINOCCHIO_IMPEDANCE_CONTROLLER_IMPORT __declspec(dllimport)
#endif
#ifdef PINOCCHIO_IMPEDANCE_CONTROLLER_BUILDING_DLL
#define PINOCCHIO_IMPEDANCE_CONTROLLER_PUBLIC PINOCCHIO_IMPEDANCE_CONTROLLER_EXPORT
#else
#define PINOCCHIO_IMPEDANCE_CONTROLLER_PUBLIC PINOCCHIO_IMPEDANCE_CONTROLLER_IMPORT
#endif
#else
#define PINOCCHIO_IMPEDANCE_CONTROLLER_EXPORT __attribute__((visibility("default")))
#define PINOCCHIO_IMPEDANCE_CONTROLLER_IMPORT
#if __GNUC__ >= 4
#define PINOCCHIO_IMPEDANCE_CONTROLLER_PUBLIC __attribute__((visibility("default")))
#else
#define PINOCCHIO_IMPEDANCE_CONTROLLER_PUBLIC
#endif
#endif

#endif  // PINOCCHIO_IMPEDANCE_CONTROLLER__VISIBILITY_CONTROL_H_
